// continuation.test.mjs - Session continuity via restore()
import assert from "node:assert/strict";
const T=[];let p=0,f=0;
function test(n,fn){T.push([n,fn]);}
function mockClineCore(){let cc=0;const sc=[],rc=[];const cline={start:async(i)=>{cc++;sc.push(i);const k=(i.config||{}).apiKey||"u";if(k.includes("k02-cp"))throw new Error("clinepass limit");if(k.includes("k03"))throw new Error("free limit");return{sessionId:"s"+cc,result:{text:"ok"+k}}},restore:async(i)=>{cc++;rc.push(i);const k=(i.start?.config||{}).apiKey||"u";return{sessionId:i.sessionId,startResult:{result:{text:"restored"+k},messages:[{role:"user",content:"Original"},{role:"assistant",content:"State"}]}}},dispose:async()=>{}};return{create:async()=>cline,cline,getStartCalls:()=>sc,getRestoreCalls:()=>rc}}
test('c: sessionId preserved',async()=>{const mock=mockClineCore();const cline=await mock.create({});const r1=await cline.start({prompt:'T',config:{apiKey:'k01-cp'}});const sid=r1.sessionId;const restored=await cline.restore({sessionId:sid,checkpointRunCount:0,restore:{messages:true},start:{prompt:'T',config:{apiKey:'k02-cp'}}});assert.equal(restored.sessionId,sid,'same sessionId')});
test('c: restore preserves messages',async()=>{const mock=mockClineCore();const cline=await mock.create({});await cline.start({prompt:'T',config:{apiKey:'k01-cp'}});const restored=await cline.restore({sessionId:'s1',checkpointRunCount:0,restore:{messages:true},start:{prompt:'T',config:{apiKey:'k02-cp'}}});assert.ok(restored.startResult?.messages?.length>0,'messages')});
test('c: tier crossing changes provider+model',async()=>{const mock=mockClineCore();const cline=await mock.create({});const r1=await cline.start({prompt:'T',config:{apiKey:'k01',providerId:'cline-pass',modelId:'cline-pass/dsv4'}});const restored=await cline.restore({sessionId:r1.sessionId,checkpointRunCount:0,restore:{messages:true},start:{prompt:'T',config:{apiKey:'k04-free',providerId:'cline',modelId:'deepseek/deepseek-v4-flash'}}});assert.equal(restored.sessionId,r1.sessionId,'same sessionId')});
test('c: no new session created',async()=>{const mock=mockClineCore();const cline=await mock.create({});const r1=await cline.start({prompt:'T',config:{apiKey:'k01'}});const restored=await cline.restore({sessionId:r1.sessionId,checkpointRunCount:0,restore:{messages:true},start:{prompt:'T',config:{apiKey:'k04-free'}}});assert.equal(restored.sessionId,r1.sessionId,'same session');assert.equal(mock.getStartCalls().length,1,'one start')});
test('c: same sessionId across multiple rollovers',async()=>{const mock=mockClineCore();const cline=await mock.create({});const r1=await cline.start({prompt:'T',config:{apiKey:'k01'}});const sid=r1.sessionId;const r2=await cline.restore({sessionId:sid,checkpointRunCount:0,restore:{messages:true},start:{prompt:'T',config:{apiKey:'k04-free'}}});assert.equal(r2.sessionId,sid,'first');const r3=await cline.restore({sessionId:sid,checkpointRunCount:0,restore:{messages:true},start:{prompt:'T',config:{apiKey:'k04-other'}}});assert.equal(r3.sessionId,sid,'second')});
async function main(){for(const[n,fn]of T){try{await fn();p++;console.log('PASS:'+n)}catch(err){f++;console.error('FAIL:'+n+'\n'+(err?.message||err))}}console.log('\n'+p+' passed, '+f+' failed.');process.exit(f>0?1:0)}main();